/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post100, git sha1 a1bb0255d) */

(* top =  1  *)
(* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:648" *)
(* generator = "Amaranth" *)
module top(cpu_rst_n, test_rst_n, rst, clk, rtc_clk, intr, rx, spi_sdi, tx, ev, spi_clk, spi_csn, spi_sdo, spi_mode, pwrup_rst_n);
  wire \$1 ;
  wire \$10 ;
  wire [3:0] \$11 ;
  wire [3:0] \$12 ;
  wire [3:0] \$13 ;
  wire [3:0] \$14 ;
  wire [3:0] \$15 ;
  wire [3:0] \$16 ;
  wire [3:0] \$17 ;
  wire [3:0] \$18 ;
  wire [3:0] \$19 ;
  wire [1:0] \$2 ;
  wire [3:0] \$20 ;
  wire [3:0] \$21 ;
  wire [3:0] \$22 ;
  wire \$23 ;
  wire \$24 ;
  wire [3:0] \$25 ;
  wire [3:0] \$26 ;
  wire [3:0] \$27 ;
  wire [3:0] \$28 ;
  wire [3:0] \$29 ;
  wire \$3 ;
  wire [3:0] \$30 ;
  wire \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:34" *)
  wire [31:0] araddr;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:34" *)
  wire [31:0] \araddr$129 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:34" *)
  wire [31:0] \araddr$164 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:34" *)
  wire [31:0] \araddr$201 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:34" *)
  wire [31:0] \araddr$240 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:34" *)
  wire [31:0] \araddr$83 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:37" *)
  wire [1:0] arburst;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:37" *)
  wire [1:0] \arburst$132 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:37" *)
  wire [1:0] \arburst$167 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:37" *)
  wire [1:0] \arburst$204 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:37" *)
  wire [1:0] \arburst$243 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:37" *)
  wire [1:0] \arburst$86 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:39" *)
  wire [3:0] arcache;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:39" *)
  wire [3:0] \arcache$134 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:39" *)
  wire [3:0] \arcache$169 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:39" *)
  wire [3:0] \arcache$206 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:39" *)
  wire [3:0] \arcache$245 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:39" *)
  wire [3:0] \arcache$88 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:33" *)
  wire [4:0] arid;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:33" *)
  wire [4:0] \arid$128 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:33" *)
  wire [4:0] \arid$163 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:33" *)
  wire [3:0] \arid$200 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:33" *)
  wire [3:0] \arid$239 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:33" *)
  wire [4:0] \arid$82 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:35" *)
  wire [7:0] arlen;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:35" *)
  wire [7:0] \arlen$130 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:35" *)
  wire [7:0] \arlen$165 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:35" *)
  wire [7:0] \arlen$202 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:35" *)
  wire [7:0] \arlen$241 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:35" *)
  wire [7:0] \arlen$84 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:38" *)
  wire arlock;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:38" *)
  wire \arlock$133 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:38" *)
  wire \arlock$168 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:38" *)
  wire \arlock$205 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:38" *)
  wire \arlock$244 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:38" *)
  wire \arlock$87 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:40" *)
  wire [2:0] arprot;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:40" *)
  wire [2:0] \arprot$135 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:40" *)
  wire [2:0] \arprot$170 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:40" *)
  wire [2:0] \arprot$207 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:40" *)
  wire [2:0] \arprot$246 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:40" *)
  wire [2:0] \arprot$89 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:43" *)
  wire [3:0] arqos;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:43" *)
  wire [3:0] \arqos$209 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:43" *)
  wire [3:0] \arqos$248 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:43" *)
  wire [3:0] \arqos$91 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:45" *)
  wire arready;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:45" *)
  wire \arready$137 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:45" *)
  wire \arready$172 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:45" *)
  wire \arready$211 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:45" *)
  wire \arready$250 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:45" *)
  wire \arready$93 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:41" *)
  wire [3:0] arregion;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:41" *)
  wire [3:0] \arregion$208 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:41" *)
  wire [3:0] \arregion$247 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:41" *)
  wire [3:0] \arregion$90 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:36" *)
  wire [2:0] arsize;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:36" *)
  wire [2:0] \arsize$131 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:36" *)
  wire [2:0] \arsize$166 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:36" *)
  wire [2:0] \arsize$203 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:36" *)
  wire [2:0] \arsize$242 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:36" *)
  wire [2:0] \arsize$85 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:44" *)
  wire arvalid;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:44" *)
  wire \arvalid$136 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:44" *)
  wire \arvalid$171 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:44" *)
  wire \arvalid$210 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:44" *)
  wire \arvalid$249 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:44" *)
  wire \arvalid$92 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:7" *)
  wire [31:0] awaddr;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:7" *)
  wire [31:0] \awaddr$110 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:7" *)
  wire [31:0] \awaddr$145 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:7" *)
  wire [31:0] \awaddr$180 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:7" *)
  wire [31:0] \awaddr$219 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:7" *)
  wire [31:0] \awaddr$71 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:10" *)
  wire [1:0] awburst;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:10" *)
  wire [1:0] \awburst$113 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:10" *)
  wire [1:0] \awburst$148 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:10" *)
  wire [1:0] \awburst$183 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:10" *)
  wire [1:0] \awburst$222 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:10" *)
  wire [1:0] \awburst$74 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:12" *)
  wire [3:0] awcache;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:12" *)
  wire [3:0] \awcache$115 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:12" *)
  wire [3:0] \awcache$150 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:12" *)
  wire [3:0] \awcache$185 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:12" *)
  wire [3:0] \awcache$224 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:12" *)
  wire [3:0] \awcache$76 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:6" *)
  wire [4:0] awid;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:6" *)
  wire [4:0] \awid$109 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:6" *)
  wire [4:0] \awid$144 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:6" *)
  wire [3:0] \awid$179 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:6" *)
  wire [3:0] \awid$218 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:6" *)
  wire [4:0] \awid$70 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:8" *)
  wire [7:0] awlen;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:8" *)
  wire [7:0] \awlen$111 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:8" *)
  wire [7:0] \awlen$146 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:8" *)
  wire [7:0] \awlen$181 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:8" *)
  wire [7:0] \awlen$220 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:8" *)
  wire [7:0] \awlen$72 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:11" *)
  wire awlock;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:11" *)
  wire \awlock$114 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:11" *)
  wire \awlock$149 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:11" *)
  wire \awlock$184 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:11" *)
  wire \awlock$223 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:11" *)
  wire \awlock$75 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:13" *)
  wire [2:0] awprot;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:13" *)
  wire [2:0] \awprot$116 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:13" *)
  wire [2:0] \awprot$151 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:13" *)
  wire [2:0] \awprot$186 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:13" *)
  wire [2:0] \awprot$225 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:13" *)
  wire [2:0] \awprot$77 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:16" *)
  wire [3:0] awqos;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:16" *)
  wire [3:0] \awqos$188 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:16" *)
  wire [3:0] \awqos$227 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:16" *)
  wire [3:0] \awqos$79 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:18" *)
  wire awready;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:18" *)
  wire \awready$118 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:18" *)
  wire \awready$153 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:18" *)
  wire \awready$190 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:18" *)
  wire \awready$229 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:18" *)
  wire \awready$81 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:14" *)
  wire [3:0] awregion;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:14" *)
  wire [3:0] \awregion$187 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:14" *)
  wire [3:0] \awregion$226 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:14" *)
  wire [3:0] \awregion$78 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:9" *)
  wire [2:0] awsize;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:9" *)
  wire [2:0] \awsize$112 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:9" *)
  wire [2:0] \awsize$147 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:9" *)
  wire [2:0] \awsize$182 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:9" *)
  wire [2:0] \awsize$221 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:9" *)
  wire [2:0] \awsize$73 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:17" *)
  wire awvalid;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:17" *)
  wire \awvalid$117 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:17" *)
  wire \awvalid$152 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:17" *)
  wire \awvalid$189 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:17" *)
  wire \awvalid$228 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:17" *)
  wire \awvalid$80 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:27" *)
  wire [4:0] bid;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:27" *)
  wire [4:0] \bid$124 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:27" *)
  wire [4:0] \bid$159 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:27" *)
  wire [3:0] \bid$196 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:27" *)
  wire [3:0] \bid$235 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:27" *)
  wire [4:0] \bid$99 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:31" *)
  wire bready;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:31" *)
  wire \bready$102 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:31" *)
  wire \bready$127 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:31" *)
  wire \bready$162 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:31" *)
  wire \bready$199 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:31" *)
  wire \bready$238 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:28" *)
  wire [1:0] bresp;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:28" *)
  wire [1:0] \bresp$100 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:28" *)
  wire [1:0] \bresp$125 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:28" *)
  wire [1:0] \bresp$160 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:28" *)
  wire [1:0] \bresp$197 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:28" *)
  wire [1:0] \bresp$236 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:29" *)
  wire bvalid;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:29" *)
  wire \bvalid$101 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:29" *)
  wire \bvalid$126 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:29" *)
  wire \bvalid$161 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:29" *)
  wire \bvalid$198 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:29" *)
  wire \bvalid$237 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:14" *)
  input clk;
  wire clk;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:17" *)
  input cpu_rst_n;
  wire cpu_rst_n;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:23" *)
  output [2:0] ev;
  wire [2:0] ev;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:20" *)
  input intr;
  wire intr;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:23" *)
  wire [13:0] paddr;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:23" *)
  wire [13:0] \paddr$25 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:25" *)
  wire penable;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:25" *)
  wire \penable$23 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:29" *)
  wire [31:0] prdata;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:29" *)
  wire [31:0] \prdata$28 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:28" *)
  wire pready;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:28" *)
  wire \pready$29 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:24" *)
  wire psel;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:24" *)
  wire \psel$26 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:30" *)
  wire pslverr;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:30" *)
  wire \pslverr$30 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:27" *)
  wire [31:0] pwdata;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:27" *)
  wire [31:0] \pwdata$27 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:26" *)
  wire pwrite;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/APB_interface.py:26" *)
  wire \pwrite$24 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:16" *)
  input pwrup_rst_n;
  wire pwrup_rst_n;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:48" *)
  wire [31:0] rdata;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:48" *)
  wire [31:0] \rdata$104 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:48" *)
  wire [31:0] \rdata$139 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:48" *)
  wire [31:0] \rdata$174 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:48" *)
  wire [31:0] \rdata$213 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:48" *)
  wire [31:0] \rdata$252 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:47" *)
  wire [4:0] rid;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:47" *)
  wire [4:0] \rid$103 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:47" *)
  wire [4:0] \rid$138 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:47" *)
  wire [4:0] \rid$173 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:47" *)
  wire [3:0] \rid$212 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:47" *)
  wire [3:0] \rid$251 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:50" *)
  wire rlast;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:50" *)
  wire \rlast$106 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:50" *)
  wire \rlast$141 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:50" *)
  wire \rlast$176 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:50" *)
  wire \rlast$215 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:50" *)
  wire \rlast$254 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:53" *)
  wire rready;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:53" *)
  wire \rready$108 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:53" *)
  wire \rready$143 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:53" *)
  wire \rready$178 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:53" *)
  wire \rready$217 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:53" *)
  wire \rready$256 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:49" *)
  wire [1:0] rresp;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:49" *)
  wire [1:0] \rresp$105 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:49" *)
  wire [1:0] \rresp$140 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:49" *)
  wire [1:0] \rresp$175 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:49" *)
  wire [1:0] \rresp$214 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:49" *)
  wire [1:0] \rresp$253 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:15" *)
  input rst;
  wire rst;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:19" *)
  input rtc_clk;
  wire rtc_clk;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:52" *)
  wire rvalid;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:52" *)
  wire \rvalid$107 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:52" *)
  wire \rvalid$142 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:52" *)
  wire \rvalid$177 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:52" *)
  wire \rvalid$216 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:52" *)
  wire \rvalid$255 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:21" *)
  input rx;
  wire rx;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:24" *)
  output spi_clk;
  wire spi_clk;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:25" *)
  output [3:0] spi_csn;
  wire [3:0] spi_csn;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:28" *)
  output [1:0] spi_mode;
  wire [1:0] spi_mode;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:26" *)
  input [3:0] spi_sdi;
  wire [3:0] spi_sdi;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:27" *)
  output [3:0] spi_sdo;
  wire [3:0] spi_sdo;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:18" *)
  input test_rst_n;
  wire test_rst_n;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:22" *)
  output tx;
  wire tx;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:20" *)
  wire [31:0] wdata;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:20" *)
  wire [31:0] \wdata$119 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:20" *)
  wire [31:0] \wdata$154 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:20" *)
  wire [31:0] \wdata$191 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:20" *)
  wire [31:0] \wdata$230 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:20" *)
  wire [31:0] \wdata$94 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:22" *)
  wire wlast;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:22" *)
  wire \wlast$121 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:22" *)
  wire \wlast$156 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:22" *)
  wire \wlast$193 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:22" *)
  wire \wlast$232 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:22" *)
  wire \wlast$96 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:25" *)
  wire wready;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:25" *)
  wire \wready$123 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:25" *)
  wire \wready$158 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:25" *)
  wire \wready$195 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:25" *)
  wire \wready$234 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:25" *)
  wire \wready$98 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:21" *)
  wire [3:0] wstrb;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:21" *)
  wire [3:0] \wstrb$120 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:21" *)
  wire [3:0] \wstrb$155 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:21" *)
  wire [3:0] \wstrb$192 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:21" *)
  wire [3:0] \wstrb$231 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:21" *)
  wire [3:0] \wstrb$95 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:24" *)
  wire wvalid;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:24" *)
  wire \wvalid$122 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:24" *)
  wire \wvalid$157 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:24" *)
  wire \wvalid$194 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:24" *)
  wire \wvalid$233 ;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/AXI_interface.py:24" *)
  wire \wvalid$97 ;
  assign \$23  = ~ (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:388" *) rst;
  assign \$24  = ~ (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:610" *) rst;
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:571" *)
  apb_spi_master #(
    .APB_ADDR_WIDTH(32'd12),
    .BUFFER_DEPTH(32'd10)
  ) apb_spi_master (
    .HCLK(clk),
    .HRESETn(rst),
    .PADDR(paddr[13:2]),
    .PENABLE(penable),
    .PRDATA(prdata),
    .PREADY(pready),
    .PSEL(psel),
    .PSLVERR(pslverr),
    .PWDATA(pwdata),
    .PWRITE(pwrite),
    .events_o(\$2 ),
    .spi_clk(spi_clk),
    .spi_csn0(\$3 ),
    .spi_csn1(\$4 ),
    .spi_csn2(\$5 ),
    .spi_csn3(\$6 ),
    .spi_mode(spi_mode),
    .spi_sdi0(spi_sdi[0]),
    .spi_sdi1(spi_sdi[1]),
    .spi_sdi2(spi_sdi[2]),
    .spi_sdi3(spi_sdi[3]),
    .spi_sdo0(\$7 ),
    .spi_sdo1(\$8 ),
    .spi_sdo2(\$9 ),
    .spi_sdo3(\$10 )
  );
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:490" *)
  apb_uart_sv #(
    .APB_ADDR_WIDTH(32'd12)
  ) apb_uart (
    .CLK(clk),
    .PADDR(\paddr$25 [13:2]),
    .PENABLE(\penable$23 ),
    .PRDATA(\prdata$28 ),
    .PREADY(\pready$29 ),
    .PSEL(\psel$26 ),
    .PSLVERR(\pslverr$30 ),
    .PWDATA(\pwdata$27 ),
    .PWRITE(\pwrite$24 ),
    .RSTN(rst),
    .event_o(\$1 ),
    .rx_i(rx),
    .tx_o(tx)
  );
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:509" *)
  axi2apb #(
    .APB_ADDR_WIDTH(32'd14),
    .AXI4_ID_WIDTH(32'd5),
    .AXI4_USER_WIDTH(32'd4)
  ) axi2apb_spi (
    .ACLK(clk),
    .ARADDR_i(\araddr$83 ),
    .ARBURST_i(\arburst$86 ),
    .ARCACHE_i(\arcache$88 ),
    .ARESETn(rst),
    .ARID_i(\arid$82 ),
    .ARLEN_i(\arlen$84 ),
    .ARLOCK_i(\arlock$87 ),
    .ARPROT_i(\arprot$89 ),
    .ARQOS_i(\arqos$91 ),
    .ARREADY_o(\arready$93 ),
    .ARREGION_i(\arregion$90 ),
    .ARSIZE_i(\arsize$85 ),
    .ARUSER_i(4'h0),
    .ARVALID_i(\arvalid$92 ),
    .AWADDR_i(\awaddr$71 ),
    .AWBURST_i(\awburst$74 ),
    .AWCACHE_i(\awcache$76 ),
    .AWID_i(\awid$70 ),
    .AWLEN_i(\awlen$72 ),
    .AWLOCK_i(\awlock$75 ),
    .AWPROT_i(\awprot$77 ),
    .AWQOS_i(\awqos$79 ),
    .AWREADY_o(\awready$81 ),
    .AWREGION_i(\awregion$78 ),
    .AWSIZE_i(\awsize$73 ),
    .AWUSER_i(4'h0),
    .AWVALID_i(\awvalid$80 ),
    .BID_o(\bid$99 ),
    .BREADY_i(\bready$102 ),
    .BRESP_o(\bresp$100 ),
    .BUSER_o(\$11 ),
    .BVALID_o(\bvalid$101 ),
    .PADDR(paddr),
    .PENABLE(penable),
    .PRDATA(prdata),
    .PREADY(pready),
    .PSEL(psel),
    .PSLVERR(pslverr),
    .PWDATA(pwdata),
    .PWRITE(pwrite),
    .RDATA_o(\rdata$104 ),
    .RID_o(\rid$103 ),
    .RLAST_o(\rlast$106 ),
    .RREADY_i(\rready$108 ),
    .RRESP_o(\rresp$105 ),
    .RUSER_o(\$12 ),
    .RVALID_o(\rvalid$107 ),
    .WDATA_i(\wdata$94 ),
    .WLAST_i(\wlast$96 ),
    .WREADY_o(\wready$98 ),
    .WSTRB_i(\wstrb$95 ),
    .WUSER_i(4'h0),
    .WVALID_i(\wvalid$97 ),
    .test_en_i(1'h0)
  );
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:427" *)
  axi2apb #(
    .APB_ADDR_WIDTH(32'd14),
    .AXI4_ID_WIDTH(32'd5),
    .AXI4_USER_WIDTH(32'd4)
  ) axi2apb_uart (
    .ACLK(clk),
    .ARADDR_i(araddr),
    .ARBURST_i(arburst),
    .ARCACHE_i(arcache),
    .ARESETn(rst),
    .ARID_i(arid),
    .ARLEN_i(arlen),
    .ARLOCK_i(arlock),
    .ARPROT_i(arprot),
    .ARQOS_i(arqos),
    .ARREADY_o(arready),
    .ARREGION_i(arregion),
    .ARSIZE_i(arsize),
    .ARUSER_i(4'h0),
    .ARVALID_i(arvalid),
    .AWADDR_i(awaddr),
    .AWBURST_i(awburst),
    .AWCACHE_i(awcache),
    .AWID_i(awid),
    .AWLEN_i(awlen),
    .AWLOCK_i(awlock),
    .AWPROT_i(awprot),
    .AWQOS_i(awqos),
    .AWREADY_o(awready),
    .AWREGION_i(awregion),
    .AWSIZE_i(awsize),
    .AWUSER_i(4'h0),
    .AWVALID_i(awvalid),
    .BID_o(bid),
    .BREADY_i(bready),
    .BRESP_o(bresp),
    .BUSER_o(\$13 ),
    .BVALID_o(bvalid),
    .PADDR(\paddr$25 ),
    .PENABLE(\penable$23 ),
    .PRDATA(\prdata$28 ),
    .PREADY(\pready$29 ),
    .PSEL(\psel$26 ),
    .PSLVERR(\pslverr$30 ),
    .PWDATA(\pwdata$27 ),
    .PWRITE(\pwrite$24 ),
    .RDATA_o(rdata),
    .RID_o(rid),
    .RLAST_o(rlast),
    .RREADY_i(rready),
    .RRESP_o(rresp),
    .RUSER_o(\$14 ),
    .RVALID_o(rvalid),
    .WDATA_i(wdata),
    .WLAST_i(wlast),
    .WREADY_o(wready),
    .WSTRB_i(wstrb),
    .WUSER_i(4'h0),
    .WVALID_i(wvalid),
    .test_en_i(1'h0)
  );
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:135" *)
  axi_intercon axi_intercon (
    .clk_i(clk),
    .i_IFU_araddr(\araddr$201 ),
    .i_IFU_arburst(\arburst$204 ),
    .i_IFU_arcache(\arcache$206 ),
    .i_IFU_arid(\arid$200 ),
    .i_IFU_arlen(\arlen$202 ),
    .i_IFU_arlock(\arlock$205 ),
    .i_IFU_arprot(\arprot$207 ),
    .i_IFU_arqos(\arqos$209 ),
    .i_IFU_arregion(\arregion$208 ),
    .i_IFU_arsize(\arsize$203 ),
    .i_IFU_arvalid(\arvalid$210 ),
    .i_IFU_awaddr(\awaddr$180 ),
    .i_IFU_awburst(\awburst$183 ),
    .i_IFU_awcache(\awcache$185 ),
    .i_IFU_awid(\awid$179 ),
    .i_IFU_awlen(\awlen$181 ),
    .i_IFU_awlock(\awlock$184 ),
    .i_IFU_awprot(\awprot$186 ),
    .i_IFU_awqos(\awqos$188 ),
    .i_IFU_awregion(\awregion$187 ),
    .i_IFU_awsize(\awsize$182 ),
    .i_IFU_awvalid(\awvalid$189 ),
    .i_IFU_bready(\bready$199 ),
    .i_IFU_rready(\rready$217 ),
    .i_IFU_wdata(\wdata$191 ),
    .i_IFU_wlast(\wlast$193 ),
    .i_IFU_wstrb(\wstrb$192 ),
    .i_IFU_wvalid(\wvalid$194 ),
    .i_LSU_araddr(\araddr$240 ),
    .i_LSU_arburst(\arburst$243 ),
    .i_LSU_arcache(\arcache$245 ),
    .i_LSU_arid(\arid$239 ),
    .i_LSU_arlen(\arlen$241 ),
    .i_LSU_arlock(\arlock$244 ),
    .i_LSU_arprot(\arprot$246 ),
    .i_LSU_arqos(\arqos$248 ),
    .i_LSU_arregion(\arregion$247 ),
    .i_LSU_arsize(\arsize$242 ),
    .i_LSU_arvalid(\arvalid$249 ),
    .i_LSU_awaddr(\awaddr$219 ),
    .i_LSU_awburst(\awburst$222 ),
    .i_LSU_awcache(\awcache$224 ),
    .i_LSU_awid(\awid$218 ),
    .i_LSU_awlen(\awlen$220 ),
    .i_LSU_awlock(\awlock$223 ),
    .i_LSU_awprot(\awprot$225 ),
    .i_LSU_awqos(\awqos$227 ),
    .i_LSU_awregion(\awregion$226 ),
    .i_LSU_awsize(\awsize$221 ),
    .i_LSU_awvalid(\awvalid$228 ),
    .i_LSU_bready(\bready$238 ),
    .i_LSU_rready(\rready$256 ),
    .i_LSU_wdata(\wdata$230 ),
    .i_LSU_wlast(\wlast$232 ),
    .i_LSU_wstrb(\wstrb$231 ),
    .i_LSU_wvalid(\wvalid$233 ),
    .i_ram_arready(\arready$137 ),
    .i_ram_awready(\awready$118 ),
    .i_ram_bid(\bid$124 ),
    .i_ram_bresp(\bresp$125 ),
    .i_ram_bvalid(\bvalid$126 ),
    .i_ram_rdata(\rdata$139 ),
    .i_ram_rid(\rid$138 ),
    .i_ram_rlast(\rlast$141 ),
    .i_ram_rresp(\rresp$140 ),
    .i_ram_rvalid(\rvalid$142 ),
    .i_ram_wready(\wready$123 ),
    .i_rom_arready(\arready$172 ),
    .i_rom_awready(\awready$153 ),
    .i_rom_bid(\bid$159 ),
    .i_rom_bresp(\bresp$160 ),
    .i_rom_bvalid(\bvalid$161 ),
    .i_rom_rdata(\rdata$174 ),
    .i_rom_rid(\rid$173 ),
    .i_rom_rlast(\rlast$176 ),
    .i_rom_rresp(\rresp$175 ),
    .i_rom_rvalid(\rvalid$177 ),
    .i_rom_wready(\wready$158 ),
    .i_spi_arready(\arready$93 ),
    .i_spi_awready(\awready$81 ),
    .i_spi_bid(\bid$99 ),
    .i_spi_bresp(\bresp$100 ),
    .i_spi_bvalid(\bvalid$101 ),
    .i_spi_rdata(\rdata$104 ),
    .i_spi_rid(\rid$103 ),
    .i_spi_rlast(\rlast$106 ),
    .i_spi_rresp(\rresp$105 ),
    .i_spi_rvalid(\rvalid$107 ),
    .i_spi_wready(\wready$98 ),
    .i_uart_arready(arready),
    .i_uart_awready(awready),
    .i_uart_bid(bid),
    .i_uart_bresp(bresp),
    .i_uart_bvalid(bvalid),
    .i_uart_rdata(rdata),
    .i_uart_rid(rid),
    .i_uart_rlast(rlast),
    .i_uart_rresp(rresp),
    .i_uart_rvalid(rvalid),
    .i_uart_wready(wready),
    .o_IFU_arready(\arready$211 ),
    .o_IFU_awready(\awready$190 ),
    .o_IFU_bid(\bid$196 ),
    .o_IFU_bresp(\bresp$197 ),
    .o_IFU_bvalid(\bvalid$198 ),
    .o_IFU_rdata(\rdata$213 ),
    .o_IFU_rid(\rid$212 ),
    .o_IFU_rlast(\rlast$215 ),
    .o_IFU_rresp(\rresp$214 ),
    .o_IFU_rvalid(\rvalid$216 ),
    .o_IFU_wready(\wready$195 ),
    .o_LSU_arready(\arready$250 ),
    .o_LSU_awready(\awready$229 ),
    .o_LSU_bid(\bid$235 ),
    .o_LSU_bresp(\bresp$236 ),
    .o_LSU_bvalid(\bvalid$237 ),
    .o_LSU_rdata(\rdata$252 ),
    .o_LSU_rid(\rid$251 ),
    .o_LSU_rlast(\rlast$254 ),
    .o_LSU_rresp(\rresp$253 ),
    .o_LSU_rvalid(\rvalid$255 ),
    .o_LSU_wready(\wready$234 ),
    .o_ram_araddr(\araddr$129 ),
    .o_ram_arburst(\arburst$132 ),
    .o_ram_arcache(\arcache$134 ),
    .o_ram_arid(\arid$128 ),
    .o_ram_arlen(\arlen$130 ),
    .o_ram_arlock(\arlock$133 ),
    .o_ram_arprot(\arprot$135 ),
    .o_ram_arqos(\$18 ),
    .o_ram_arregion(\$17 ),
    .o_ram_arsize(\arsize$131 ),
    .o_ram_arvalid(\arvalid$136 ),
    .o_ram_awaddr(\awaddr$110 ),
    .o_ram_awburst(\awburst$113 ),
    .o_ram_awcache(\awcache$115 ),
    .o_ram_awid(\awid$109 ),
    .o_ram_awlen(\awlen$111 ),
    .o_ram_awlock(\awlock$114 ),
    .o_ram_awprot(\awprot$116 ),
    .o_ram_awqos(\$16 ),
    .o_ram_awregion(\$15 ),
    .o_ram_awsize(\awsize$112 ),
    .o_ram_awvalid(\awvalid$117 ),
    .o_ram_bready(\bready$127 ),
    .o_ram_rready(\rready$143 ),
    .o_ram_wdata(\wdata$119 ),
    .o_ram_wlast(\wlast$121 ),
    .o_ram_wstrb(\wstrb$120 ),
    .o_ram_wvalid(\wvalid$122 ),
    .o_rom_araddr(\araddr$164 ),
    .o_rom_arburst(\arburst$167 ),
    .o_rom_arcache(\arcache$169 ),
    .o_rom_arid(\arid$163 ),
    .o_rom_arlen(\arlen$165 ),
    .o_rom_arlock(\arlock$168 ),
    .o_rom_arprot(\arprot$170 ),
    .o_rom_arqos(\$22 ),
    .o_rom_arregion(\$21 ),
    .o_rom_arsize(\arsize$166 ),
    .o_rom_arvalid(\arvalid$171 ),
    .o_rom_awaddr(\awaddr$145 ),
    .o_rom_awburst(\awburst$148 ),
    .o_rom_awcache(\awcache$150 ),
    .o_rom_awid(\awid$144 ),
    .o_rom_awlen(\awlen$146 ),
    .o_rom_awlock(\awlock$149 ),
    .o_rom_awprot(\awprot$151 ),
    .o_rom_awqos(\$20 ),
    .o_rom_awregion(\$19 ),
    .o_rom_awsize(\awsize$147 ),
    .o_rom_awvalid(\awvalid$152 ),
    .o_rom_bready(\bready$162 ),
    .o_rom_rready(\rready$178 ),
    .o_rom_wdata(\wdata$154 ),
    .o_rom_wlast(\wlast$156 ),
    .o_rom_wstrb(\wstrb$155 ),
    .o_rom_wvalid(\wvalid$157 ),
    .o_spi_araddr(\araddr$83 ),
    .o_spi_arburst(\arburst$86 ),
    .o_spi_arcache(\arcache$88 ),
    .o_spi_arid(\arid$82 ),
    .o_spi_arlen(\arlen$84 ),
    .o_spi_arlock(\arlock$87 ),
    .o_spi_arprot(\arprot$89 ),
    .o_spi_arqos(\arqos$91 ),
    .o_spi_arregion(\arregion$90 ),
    .o_spi_arsize(\arsize$85 ),
    .o_spi_arvalid(\arvalid$92 ),
    .o_spi_awaddr(\awaddr$71 ),
    .o_spi_awburst(\awburst$74 ),
    .o_spi_awcache(\awcache$76 ),
    .o_spi_awid(\awid$70 ),
    .o_spi_awlen(\awlen$72 ),
    .o_spi_awlock(\awlock$75 ),
    .o_spi_awprot(\awprot$77 ),
    .o_spi_awqos(\awqos$79 ),
    .o_spi_awregion(\awregion$78 ),
    .o_spi_awsize(\awsize$73 ),
    .o_spi_awvalid(\awvalid$80 ),
    .o_spi_bready(\bready$102 ),
    .o_spi_rready(\rready$108 ),
    .o_spi_wdata(\wdata$94 ),
    .o_spi_wlast(\wlast$96 ),
    .o_spi_wstrb(\wstrb$95 ),
    .o_spi_wvalid(\wvalid$97 ),
    .o_uart_araddr(araddr),
    .o_uart_arburst(arburst),
    .o_uart_arcache(arcache),
    .o_uart_arid(arid),
    .o_uart_arlen(arlen),
    .o_uart_arlock(arlock),
    .o_uart_arprot(arprot),
    .o_uart_arqos(arqos),
    .o_uart_arregion(arregion),
    .o_uart_arsize(arsize),
    .o_uart_arvalid(arvalid),
    .o_uart_awaddr(awaddr),
    .o_uart_awburst(awburst),
    .o_uart_awcache(awcache),
    .o_uart_awid(awid),
    .o_uart_awlen(awlen),
    .o_uart_awlock(awlock),
    .o_uart_awprot(awprot),
    .o_uart_awqos(awqos),
    .o_uart_awregion(awregion),
    .o_uart_awsize(awsize),
    .o_uart_awvalid(awvalid),
    .o_uart_bready(bready),
    .o_uart_rready(rready),
    .o_uart_wdata(wdata),
    .o_uart_wlast(wlast),
    .o_uart_wstrb(wstrb),
    .o_uart_wvalid(wvalid),
    .rst_ni(rst)
  );
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:381" *)
  axi_ram #(
    .ADDR_WIDTH(32'd32),
    .DATA_WIDTH(32'd32),
    .ID_WIDTH(32'd5),
    .MEM_INIT("config/RAM.hex")
  ) axi_ram (
    .clk(clk),
    .rst(\$23 ),
    .s_axi_araddr(\araddr$129 ),
    .s_axi_arburst(\arburst$132 ),
    .s_axi_arcache(\arcache$134 ),
    .s_axi_arid(\arid$128 ),
    .s_axi_arlen(\arlen$130 ),
    .s_axi_arlock(\arlock$133 ),
    .s_axi_arprot(\arprot$135 ),
    .s_axi_arready(\arready$137 ),
    .s_axi_arsize(\arsize$131 ),
    .s_axi_arvalid(\arvalid$136 ),
    .s_axi_awaddr(\awaddr$110 ),
    .s_axi_awburst(\awburst$113 ),
    .s_axi_awcache(\awcache$115 ),
    .s_axi_awid(\awid$109 ),
    .s_axi_awlen(\awlen$111 ),
    .s_axi_awlock(\awlock$114 ),
    .s_axi_awprot(\awprot$116 ),
    .s_axi_awready(\awready$118 ),
    .s_axi_awsize(\awsize$112 ),
    .s_axi_awvalid(\awvalid$117 ),
    .s_axi_bid(\bid$124 ),
    .s_axi_bready(\bready$127 ),
    .s_axi_bresp(\bresp$125 ),
    .s_axi_bvalid(\bvalid$126 ),
    .s_axi_rdata(\rdata$139 ),
    .s_axi_rid(\rid$138 ),
    .s_axi_rlast(\rlast$141 ),
    .s_axi_rready(\rready$143 ),
    .s_axi_rresp(\rresp$140 ),
    .s_axi_rvalid(\rvalid$142 ),
    .s_axi_wdata(\wdata$119 ),
    .s_axi_wlast(\wlast$121 ),
    .s_axi_wready(\wready$123 ),
    .s_axi_wstrb(\wstrb$120 ),
    .s_axi_wvalid(\wvalid$122 )
  );
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:603" *)
  axi_ram #(
    .ADDR_WIDTH(32'd32),
    .DATA_WIDTH(32'd32),
    .ID_WIDTH(32'd5),
    .MEM_INIT("config/RAM.hex")
  ) axi_rom (
    .clk(clk),
    .rst(\$24 ),
    .s_axi_araddr(\araddr$164 ),
    .s_axi_arburst(\arburst$167 ),
    .s_axi_arcache(\arcache$169 ),
    .s_axi_arid(\arid$163 ),
    .s_axi_arlen(\arlen$165 ),
    .s_axi_arlock(\arlock$168 ),
    .s_axi_arprot(\arprot$170 ),
    .s_axi_arready(\arready$172 ),
    .s_axi_arsize(\arsize$166 ),
    .s_axi_arvalid(\arvalid$171 ),
    .s_axi_awaddr(\awaddr$145 ),
    .s_axi_awburst(\awburst$148 ),
    .s_axi_awcache(\awcache$150 ),
    .s_axi_awid(\awid$144 ),
    .s_axi_awlen(\awlen$146 ),
    .s_axi_awlock(\awlock$149 ),
    .s_axi_awprot(\awprot$151 ),
    .s_axi_awready(\awready$153 ),
    .s_axi_awsize(\awsize$147 ),
    .s_axi_awvalid(\awvalid$152 ),
    .s_axi_bid(\bid$159 ),
    .s_axi_bready(\bready$162 ),
    .s_axi_bresp(\bresp$160 ),
    .s_axi_bvalid(\bvalid$161 ),
    .s_axi_rdata(\rdata$174 ),
    .s_axi_rid(\rid$173 ),
    .s_axi_rlast(\rlast$176 ),
    .s_axi_rready(\rready$178 ),
    .s_axi_rresp(\rresp$175 ),
    .s_axi_rvalid(\rvalid$177 ),
    .s_axi_wdata(\wdata$154 ),
    .s_axi_wlast(\wlast$156 ),
    .s_axi_wready(\wready$158 ),
    .s_axi_wstrb(\wstrb$155 ),
    .s_axi_wvalid(\wvalid$157 )
  );
  (* src = "/home/abdul/amaranth/SoC_AR_SCR1/python/top_level.py:31" *)
  scr1_top_axi cpu_core (
    .clk(clk),
    .cpu_rst_n(cpu_rst_n),
    .ext_irq(1'h0),
    .fuse_mhartid(32'd0),
    .io_axi_dmem_araddr(\araddr$240 ),
    .io_axi_dmem_arburst(\arburst$243 ),
    .io_axi_dmem_arcache(\arcache$245 ),
    .io_axi_dmem_arid(\arid$239 ),
    .io_axi_dmem_arlen(\arlen$241 ),
    .io_axi_dmem_arlock(\arlock$244 ),
    .io_axi_dmem_arprot(\arprot$246 ),
    .io_axi_dmem_arqos(\arqos$248 ),
    .io_axi_dmem_arready(\arready$250 ),
    .io_axi_dmem_arregion(\arregion$247 ),
    .io_axi_dmem_arsize(\arsize$242 ),
    .io_axi_dmem_aruser(\$30 ),
    .io_axi_dmem_arvalid(\arvalid$249 ),
    .io_axi_dmem_awaddr(\awaddr$219 ),
    .io_axi_dmem_awburst(\awburst$222 ),
    .io_axi_dmem_awcache(\awcache$224 ),
    .io_axi_dmem_awid(\awid$218 ),
    .io_axi_dmem_awlen(\awlen$220 ),
    .io_axi_dmem_awlock(\awlock$223 ),
    .io_axi_dmem_awprot(\awprot$225 ),
    .io_axi_dmem_awqos(\awqos$227 ),
    .io_axi_dmem_awready(\awready$229 ),
    .io_axi_dmem_awregion(\awregion$226 ),
    .io_axi_dmem_awsize(\awsize$221 ),
    .io_axi_dmem_awuser(\$28 ),
    .io_axi_dmem_awvalid(\awvalid$228 ),
    .io_axi_dmem_bid(\bid$235 ),
    .io_axi_dmem_bready(\bready$238 ),
    .io_axi_dmem_bresp(\bresp$236 ),
    .io_axi_dmem_buser(4'h0),
    .io_axi_dmem_bvalid(\bvalid$237 ),
    .io_axi_dmem_rdata(\rdata$252 ),
    .io_axi_dmem_rid(\rid$251 ),
    .io_axi_dmem_rlast(\rlast$254 ),
    .io_axi_dmem_rready(\rready$256 ),
    .io_axi_dmem_rresp(\rresp$253 ),
    .io_axi_dmem_ruser(4'h0),
    .io_axi_dmem_rvalid(\rvalid$255 ),
    .io_axi_dmem_wdata(\wdata$230 ),
    .io_axi_dmem_wlast(\wlast$232 ),
    .io_axi_dmem_wready(\wready$234 ),
    .io_axi_dmem_wstrb(\wstrb$231 ),
    .io_axi_dmem_wuser(\$29 ),
    .io_axi_dmem_wvalid(\wvalid$233 ),
    .io_axi_imem_araddr(\araddr$201 ),
    .io_axi_imem_arburst(\arburst$204 ),
    .io_axi_imem_arcache(\arcache$206 ),
    .io_axi_imem_arid(\arid$200 ),
    .io_axi_imem_arlen(\arlen$202 ),
    .io_axi_imem_arlock(\arlock$205 ),
    .io_axi_imem_arprot(\arprot$207 ),
    .io_axi_imem_arqos(\arqos$209 ),
    .io_axi_imem_arready(\arready$211 ),
    .io_axi_imem_arregion(\arregion$208 ),
    .io_axi_imem_arsize(\arsize$203 ),
    .io_axi_imem_aruser(\$27 ),
    .io_axi_imem_arvalid(\arvalid$210 ),
    .io_axi_imem_awaddr(\awaddr$180 ),
    .io_axi_imem_awburst(\awburst$183 ),
    .io_axi_imem_awcache(\awcache$185 ),
    .io_axi_imem_awid(\awid$179 ),
    .io_axi_imem_awlen(\awlen$181 ),
    .io_axi_imem_awlock(\awlock$184 ),
    .io_axi_imem_awprot(\awprot$186 ),
    .io_axi_imem_awqos(\awqos$188 ),
    .io_axi_imem_awready(\awready$190 ),
    .io_axi_imem_awregion(\awregion$187 ),
    .io_axi_imem_awsize(\awsize$182 ),
    .io_axi_imem_awuser(\$25 ),
    .io_axi_imem_awvalid(\awvalid$189 ),
    .io_axi_imem_bid(\bid$196 ),
    .io_axi_imem_bready(\bready$199 ),
    .io_axi_imem_bresp(\bresp$197 ),
    .io_axi_imem_buser(4'h0),
    .io_axi_imem_bvalid(\bvalid$198 ),
    .io_axi_imem_rdata(\rdata$213 ),
    .io_axi_imem_rid(\rid$212 ),
    .io_axi_imem_rlast(\rlast$215 ),
    .io_axi_imem_rready(\rready$217 ),
    .io_axi_imem_rresp(\rresp$214 ),
    .io_axi_imem_ruser(4'h0),
    .io_axi_imem_rvalid(\rvalid$216 ),
    .io_axi_imem_wdata(\wdata$191 ),
    .io_axi_imem_wlast(\wlast$193 ),
    .io_axi_imem_wready(\wready$195 ),
    .io_axi_imem_wstrb(\wstrb$192 ),
    .io_axi_imem_wuser(\$26 ),
    .io_axi_imem_wvalid(\wvalid$194 ),
    .pwrup_rst_n(pwrup_rst_n),
    .rst_n(rst),
    .rtc_clk(rtc_clk),
    .soft_irq(1'h0),
    .test_mode(1'h0),
    .test_rst_n(test_rst_n)
  );
  assign ev = { \$2 , \$1  };
  assign spi_csn = { \$6 , \$5 , \$4 , \$3  };
  assign spi_sdo = { \$10 , \$9 , \$8 , \$7  };
endmodule
